# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- push

pool:
  vmImage: windows-latest

jobs:
- job: BuildDebug
  displayName: Build Debug
  variables:
    solution: '.\SimpleCalculations\SimpleCalculations.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'
  steps:
  - task: NuGetToolInstaller@1
#  - task: NuGetCommand@2
#    inputs:
#      restoreSolution: '$(solution)'
#  - task: VSBuild@1
#    inputs:
#      solution: '$(solution)'
#      platform: '$(buildPlatform)'
#      configuration: '$(buildConfiguration)'
#      restoreNugetPackages: true

- job: BuildRelease
  displayName: Build Release
  dependsOn: BuildDebug
  variables:
    solution: '.\SimpleCalculations\SimpleCalculations.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    disableable.coverage: true

  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
      

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      #msbuildArgs: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourceDirectory)/TestResults/Coverage/'
  
  - script: dotnet test $(solution) -c Release --collect:"XPlat Code Coverage"
    displayName: Test

  - script: dotnet tool install -g dotnet-reportgenerator-globaltool
    displayName: Install Reportgenerator
  - script: reportgenerator -reports:".\SimpleCalculations\SimpleCalculations.Tests\TestResults\**\coverage.cobertura.xml" -targetdir:"./Coverage" -reporttypes:Html
    displayName: Create Report

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '.\SimpleCalculations\SimpleCalculations.Tests\TestResults\**\coverage.cobertura.xml'
# stage B runs if A fails
#- stage: B
#  condition: tag

# stage C runs if B succeeds
#- stage: C
#  dependsOn:
#  - A
#  - B
#  condition: succeeded('B')
