# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- push

pool:
  vmImage: windows-latest

jobs:
- job: BuildDebug
  displayName: Build Debug
  variables:
    solution: '.\SimpleCalculations\SimpleCalculations.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Debug'
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      restoreNugetPackages: true

- job: BuildRelease
  displayName: Build Release
  dependsOn: BuildDebug
  variables:
    solution: '.\SimpleCalculations\SimpleCalculations.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    disableable.coverage: true

  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
      
  - script: rktracer -vs -on '$(solution)'
    displayName: RKTracer
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
  
  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: rkresults -xml -nolaunch
    displayName: RKResults

# stage B runs if A fails
#- stage: B
#  condition: tag

# stage C runs if B succeeds
#- stage: C
#  dependsOn:
#  - A
#  - B
#  condition: succeeded('B')
