name: .NET

on:
  push:
    branches: 
      - '**'
    tags:        
      - '**'

env:
  PROJECT_PATH: SimpleCalculations\SimpleCalculations.sln
  CONFIGURATION: Debug

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3

    - shell: bash
      run: |
        pwd

    - run: ls

    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore SimpleCalculations\SimpleCalculations.sln

    - name: Build
      run: dotnet build $PROJECT_PATH --no-restore --configuration $CONFIGURATION

    - name: Test
      run: dotnet test $PROJECT_PATH --no-build --verbosity normal


#if: startsWith(github.ref, 'refs/tags/v')